- pruebaResolved.txt
> Prueba resuelto

- pruebaResolved.txt
Terminé de resolver el problema que se me encargó.
#11
> problema resuelto

- index.html
> Finalización del botón de búsqueda

- index.html
ddfjfjjeffjdfjfejfijsjfijfaksjfJFIJDFKJFIJFKJASKDASJDIQOWJSADJQOJWEJDAOIDQLKWJDAOIJADJOQIJWLaodqlkjdsiqlkjwoisjdlqiwejsdialwkdsalwkjd
#16
> Finalización del botón de suscripción

- index.html
asdasdasdasdasdasdasdasdasdasd
#18
> Finalización de la prueba

- assets/html/tienda.html
- index.html
se a solucionado el error de los enlaces en mi tienda.html
> solucion del error de enlaces

- assets/html/page_of_product.html
> Solución de errores de pagina de producto

- assets/css/page_of_product_style.css
- assets/html/page_of_product.html
Se actualizo el header, se cambio el color al pasar el mouse por encima de las rutas y se creo un nuevo div llamado "product-detail" donde se agrego el div "product" que contiene las imágenes del producto y un nuevo div "description" ubicado al lado derecho de las imágenes del producto y en el cual ira la descripción del producto seleccionado por el usuario.
> Inserción de la descripción del producto

- assets/css/filtro.css
- assets/css/filtro2.css
- assets/html/tienda.html
Se agragado las siguientes funciones:
- se a puesto un orden o menu desplegable
- se a puesto una ruta de seguimiento
> orden visualizacion y ruta

- assets/css/filtro.css
- assets/html/tienda.html
se agragado una descripcion en la parte del titulo principal llamado "LIBROS"
> descripcion para la pagina de libros

- assets/css/style.css
- index.html
Estoy uniendo la rama de desarrollo con la de produccion para empezar a sacar todas nuestras ramas a partir de la rama de dev y ya NO de main
> Uniendo entorno dev con prod

- assets/css/page_of_product_style.css
- assets/html/page_of_product.html
- assets/js/page_of_product.js
Se agrego el botón de cantidad debajo de la descripción del producto, los iconos de suma y resta al presionarlos aumenta o reduce el numero mostrado.
> Implementación del botón de cantidad

- assets/css/detalleProducto.css
- assets/css/filtro.css
- assets/html/detalleProducto.html
- assets/html/tienda.html
En esta solicitud se esta agregando la parte de los libros relacionados, se utilizo de ayuda el código del compañero Yeshua para el orden de los libros.
> Implementación de los libros relacionados

- assets/css/style.css
- index.html
Termine de agregar los libros en tendencia + responsive
> seccion de libros en tendencia completa

- index.html
Borrando dos items innecesarios al proyecto
> elimando items innecesarios

- assets/css/style.css
- index.html
Termine implementando el registro de correos
> 47 registro de correo inicio

- assets/css/tabla-carrito.css
- assets/html/carrito-de-compra.html
- assets/js/contador.js
- index.html
se ha colocado una tabla en la pestaña carrito de compras
nota: espero mi 20 master
> tabla de los productos #36

- assets/css/tabla-carrito.css
- assets/html/carrito-de-compra.html
- assets/js/contador.js
- index.html
Se esta integrando el tablero dentro del carrito de compras, junto a sus enlaces y direcciones asociadas al espacio correspondiente.
> Union dev a main

- css/libro-oferta.css
- js/libro-oferta.js
- libro-oferta.html
Reutilice la vista de detalle-libro para adaptar con un pequeño mensaje de oferta al lado de la descripcion del libro
> insertando vista de libro en oferta

- css/tienda.css
- js/tienda.js
- tienda.html
He actualizado la vista de tienda agregando los filtros en checkboxs + titulo y descripcion de la pagina + lista de carrito de compras. Todo cuenta con su respectivo responsive
> 83 refactorizar y ordenar tienda

- carrito-compras.html
- css/carrito-compras.css
- js/carrito-compras.js
Actualice el archivo tanto html como css. Por parte del js no vi la necesidad de agregarlo ya que es solo estatico, solo reutilice los scripts que ya teniamos.
Adjunto imagen del resultado:
> Refactorizacion de la vista de Carrito de Compras

- carrito-compras.html
- css/revision-pedido.css
- detalle-libro.html
- index.html
- js/revision-pedido.js
- libro-oferta.html
- revision-pedido.html
- tienda.html
Agregue archivos tanto html como css y js. Solo reutilice los scripts y algunos estilos que ya teniamos.
Adjunto imagen del resultado:
Para una mejor vista puedes entrar al enlace del Preview propocionado por Vercel en la parte de abajo ⬇⬇⬇⬇⬇
> Insertando vista de Revision de Pedido

- carrito-compras.html
- costos-de-envio.html
- css/costo-de-envio.css
- detalle-libro.html
- index.html
- libro-oferta.html
- revision-pedido.html
- tienda.html
se ha creado la pagina de costo de envio con informacion para el cliente
> 100 crear vista de costos de envio frontend
